### ISSUE TITLE
2D array validation not working

### ISSUE THREAD

**Issue by joicemjoseph** [KaneCohen/laravel-validation#2]
two diamentional input arrays' validation are not working. as I exppexted. 
How I used is as follows.
`'c:*:a' => 'required'`
and `c` is the array name.
I escaped using `*` is 1..n and `a` is name of the field.
please help to solve this.

**Comment by KaneCohen** [comment]
Hi, could you show me your input? Tests for validation are passing, so it should be working correctly.

**Comment by joicemjoseph** [comment]
`{{ Form::text("c[$i][a]", null, array('class' => 'col-md-5 col-md-offset-4')) }}`
this is the code which iterates and generates n textfields and it fails to validate.

**Comment by KaneCohen** [comment]
Well, code seems correct. Try doing `dd(Input::all());` just to make sure that data is available.

If data is correct check your `app.php` file in config directory and make sure that service provider is there.

**Comment by joicemjoseph** [comment]
yes the provider is there and all the conf stuffs are done and running correctly
`'providers' => array(`
`'Cohensive\Validation\ValidationServiceProvider',`
`)`

**Comment by KaneCohen** [comment]
What about `dd()`? Does data look correct? Something lik thise:

````php
[
    'c' => [
        0 => ['a' => 'text'],
        1 => ['a' => 'text'],
    ]
]
````

**Comment by joicemjoseph** [comment]
like the code you listed above

**Comment by KaneCohen** [comment]
Hmm, just to make sure - what Laravel version are you using?

Also - where does `Cohensive\Validation\ValidationServiceProvider` located in providers array?
If in that array you have `Illuminate\Validation\ValidationServiceProvider` then you should put package service provider *below* core validation service provider, otherwise core service provider will override package service provider.
